### ISSUE TITLE
"AttributeError: 'module' object has no attribute 'test_forwards'" when running tests

### ISSUE THREAD

**Issue by regnat** [epsy/sigtools#4]
It looks like there's a problem with the test suite :
running `python setup.py test` fails on my machine with :

```
File "setup.py", line 33, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/1iv3krxr5dlvq7dwqsqggrp8431dwyah-python3.4m-setuptools-19.4/lib/python3.4/site-packages/setuptools-19.4-py3.4.egg/setuptools/command/test.py", line 159, in run
  File "/nix/store/1iv3krxr5dlvq7dwqsqggrp8431dwyah-python3.4m-setuptools-19.4/lib/python3.4/site-packages/setuptools-19.4-py3.4.egg/setuptools/command/test.py", line 140, in with_project_on_sys_path
  File "/nix/store/1iv3krxr5dlvq7dwqsqggrp8431dwyah-python3.4m-setuptools-19.4/lib/python3.4/site-packages/setuptools-19.4-py3.4.egg/setuptools/command/test.py", line 180, in run_tests
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/loader.py", line 157, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/loader.py", line 157, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/loader.py", line 128, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/1iv3krxr5dlvq7dwqsqggrp8431dwyah-python3.4m-setuptools-19.4/lib/python3.4/site-packages/setuptools-19.4-py3.4.egg/setuptools/command/test.py", line 38, in loadTestsFromModule
  File "/nix/store/mb8v8q5f3mx926fvmm76r38p253g2p1i-python3-3.4.4/lib/python3.4/unittest/loader.py", line 125, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_forwards'
```

**Comment by epsy** [comment]
Does it also happen when you use ``python -m unittest``?

Is there an error when you run ``python -c "import sigtools.tests.test_forwards" `` ?

**Comment by regnat** [comment]
`python -m unittest` runs fine, provided `mock` and `sphinx` are installed.
`python -c "import sigtools.tests.test_forwards"` says that the module `repeated_test` is missing :

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sigtools/tests/test_forwards.py", line 26, in <module>
    from sigtools.tests.util import Fixtures
  File "sigtools/tests/util.py", line 26, in <module>
    from repeated_test import tup, WithTestClass
ImportError: No module named repeated_test
```

**Comment by regnat** [comment]
Oh, i just see that repeated_test is an external package. I try with it installed.

**Comment by regnat** [comment]
With `repeated_test` installed, the test passes :) -- but repeated_test's tests are failing :(

**Comment by epsy** [comment]
Oh right. Those dependencies are only pulled in through tox. (``tox -e  py34``), which is the recommended easy to run sigtools tests. I'll remove the parameter from setup.py

**Comment by epsy** [comment]
Can you give a traceback of the errors?

**Comment by regnat** [comment]
Oh, I see. It works with tox, indeed :)

You mean the errors on `repeated_test` ?

**Comment by epsy** [comment]
Yeah. Or did you mean that project itself?

On Thu, Apr 21, 2016, 10:50 Théophane Hufschmitt <notifications@github.com>
wrote:

> Oh, I see. It works with tox, indeed :)
>
> You mean the errors on repeated_test ?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/epsy/sigtools/issues/4#issuecomment-212817260>
>
-- 
Yann Kaiser
kaiser.yann@gmail.com
yann.kaiser@efrei.net
+33 6 51 64 01 89
https://github.com/epsy

**Comment by regnat** [comment]
Eventually, almost everything is working with all the dependencies installed (or with tox, but I'd rather avoid using it).
The only non working thing is `python setup.py test` which raises a syntax error on python 2.7, but by using `test_suite = unittest2.collector` in setup.py, everything works fine.

If you're okay with that, I'll make a pr to change this -- and maybe add the dependencies --, so that people can run the tests directly with the setuptools

**Comment by epsy** [comment]
That would be great. Do you want a quick backport?

Setuptools allows a tests_requires option IIRC

On Thu, Apr 21, 2016, 14:39 Théophane Hufschmitt <notifications@github.com>
wrote:

> Eventually, almost everything is working with all the dependencies
> installed (or with tox, but I'd rather avoid using it).
> The only non working thing is python setup.py test which raises a syntax
> error on python 2.7, but by using test_suite = unittest2.collector in
> setup.py, everything works fine.
>
> If you're okay with that, I'll make a pr to change this -- and maybe add
> the dependencies --, so that people can run the tests directly with the
> setuptools
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/epsy/sigtools/issues/4#issuecomment-212900462>
>
-- 
Yann Kaiser
kaiser.yann@gmail.com
yann.kaiser@efrei.net
+33 6 51 64 01 89
https://github.com/epsy

**Comment by regnat** [comment]
Ok, I submit the pr asap (well, the prs in fact because there will be one for repeated_test too).

No thanks for the backport, now that I have a patch, it can wait until the next release ;)
